Repository JungleMinds/JM_API-Boilerplate, pull requests merged in 2018-11, with the labels that each got.

#17 Feature/add database infrastructure
  .circleci/config.yml
  .dockerignore
  .env
  .gitignore
  .sequelizerc
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/app/Application.js
  src/app/Application.spec.js
  src/config/environments/development.js
  src/config/environments/production.js
  src/config/environments/test.js
  src/container.js
  src/container.spec.js
  src/infrastructure/database/models/UserModel.js
  src/infrastructure/database/models/index.js
Labels: Review Required, enhancement

#18 add dependencies up to date in readme
  README.md
Labels: Review Required, enhancement

#22 Added multi-threading support to the test script
  scripts/test.js
Labels: enhancement

#24 update readme with Prerequisites and Quick Start
  README.md
Labels: Review Required

#25 Removed adminer from container
  .env
  docker-compose.yml
Labels: bug

#30 lock event-stream to v3.3.4
  package-lock.json
  package.json
Labels: bug
